# Generated by Django 5.0.14 on 2025-11-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HandoverSignatureAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(blank=True, max_length=255)),
                ("bundle_hash", models.CharField(max_length=64, unique=True)),
                ("signed_at", models.DateTimeField()),
                ("signature", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-signed_at"],
            },
        ),
    ]
