# Generated by Django 5.0.14 on 2026-02-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_auditevent_clientauditevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemoPatient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=64, unique=True)),
                ("given_name", models.CharField(max_length=128)),
                ("family_name", models.CharField(max_length=128)),
                ("gender", models.CharField(default="unknown", max_length=32)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("unit_id", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["family_name", "given_name"],
            },
        ),
    ]
