# Generated by Django 5.0.14 on 2026-02-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_patient_patient_uniq_patient_identifier_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="external_fhir_id",
            field=models.CharField(blank=True, null=True, max_length=128),
        ),
        migrations.AddField(
            model_name="patient",
            name="external_reference",
            field=models.CharField(blank=True, null=True, max_length=255),
        ),
        migrations.AddField(
            model_name="patient",
            name="fhir_sync_enabled",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="fhir_sync_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="last_fhir_sync_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="synced_to_fhir",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
