# Generated by Django 5.0.14 on 2026-03-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_patient_external_fhir_id_patient_external_reference_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IceaOutboundEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("request_id", models.CharField(max_length=255, unique=True)),
                ("bundle_id", models.CharField(db_index=True, max_length=255)),
                ("patient_id", models.CharField(db_index=True, max_length=255)),
                ("unit_id", models.CharField(db_index=True, max_length=255)),
                ("payload_json", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("sent", "Sent"), ("error", "Error")],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("next_retry_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [models.Index(fields=["status", "next_retry_at"], name="idx_icea_status_retry")],
            },
        ),
    ]
