# Generated by Django 5.0.14 on 2026-03-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_iceaoutboundevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="HandoverBundleRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bundle_id", models.CharField(max_length=255, unique=True)),
                ("patient_id", models.CharField(db_index=True, max_length=255)),
                ("unit_id", models.CharField(db_index=True, max_length=255)),
                ("request_id", models.CharField(max_length=255, unique=True)),
                ("bundle_json", models.JSONField()),
                ("encryption_metadata", models.JSONField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["bundle_id"], name="idx_handover_bundle_id"),
                    models.Index(
                        fields=["unit_id", "created_at"],
                        name="idx_handover_unit_created",
                    ),
                    models.Index(fields=["created_at"], name="idx_handover_created_at"),
                ],
            },
        ),
    ]
