FROM node:20-slim AS builder

WORKDIR /app

ENV EXPO_NO_TELEMETRY=1

RUN corepack enable
RUN corepack prepare pnpm@10 --activate

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN pnpm -w install --frozen-lockfile

COPY . .

ARG EXPO_PUBLIC_API_BASE_URL
ARG EXPO_PUBLIC_FHIR_BASE_URL
ARG EXPO_PUBLIC_ALLOWED_UNITS
ARG EXPO_PUBLIC_ALLOW_ALL_UNITS
ARG EXPO_PUBLIC_BYPASS_SCOPE
ARG EXPO_PUBLIC_STORAGE_NAMESPACE
ARG EXPO_PUBLIC_OFFLINE_REPLAY_MAX_ATTEMPTS
ARG EXPO_PUBLIC_QUEUE_BACKOFF_BASE
ARG EXPO_PUBLIC_FAST_VALIDATE_BEFORE_QUEUE
ARG EXPO_PUBLIC_CLIENT_SIGNING_ENABLED
ARG EXPO_PUBLIC_HANDOVER_FHIR_VALIDATION_MODE
ARG EXPO_PUBLIC_OFFLINE_ENCRYPTION_DISABLED
ARG EXPO_PUBLIC_ENABLE_DEMO
ARG OIDC_ISSUER
ARG OIDC_CLIENT_ID
ARG OIDC_AUDIENCE
ARG OIDC_SCOPE
ARG OIDC_REDIRECT_SCHEME

ENV NODE_ENV=production
ENV EXPO_PUBLIC_API_BASE_URL=$EXPO_PUBLIC_API_BASE_URL
ENV EXPO_PUBLIC_FHIR_BASE_URL=$EXPO_PUBLIC_FHIR_BASE_URL
ENV EXPO_PUBLIC_ALLOWED_UNITS=$EXPO_PUBLIC_ALLOWED_UNITS
ENV EXPO_PUBLIC_ALLOW_ALL_UNITS=$EXPO_PUBLIC_ALLOW_ALL_UNITS
ENV EXPO_PUBLIC_BYPASS_SCOPE=$EXPO_PUBLIC_BYPASS_SCOPE
ENV EXPO_PUBLIC_STORAGE_NAMESPACE=$EXPO_PUBLIC_STORAGE_NAMESPACE
ENV EXPO_PUBLIC_OFFLINE_REPLAY_MAX_ATTEMPTS=$EXPO_PUBLIC_OFFLINE_REPLAY_MAX_ATTEMPTS
ENV EXPO_PUBLIC_QUEUE_BACKOFF_BASE=$EXPO_PUBLIC_QUEUE_BACKOFF_BASE
ENV EXPO_PUBLIC_FAST_VALIDATE_BEFORE_QUEUE=$EXPO_PUBLIC_FAST_VALIDATE_BEFORE_QUEUE
ENV EXPO_PUBLIC_CLIENT_SIGNING_ENABLED=$EXPO_PUBLIC_CLIENT_SIGNING_ENABLED
ENV EXPO_PUBLIC_HANDOVER_FHIR_VALIDATION_MODE=$EXPO_PUBLIC_HANDOVER_FHIR_VALIDATION_MODE
ENV EXPO_PUBLIC_OFFLINE_ENCRYPTION_DISABLED=$EXPO_PUBLIC_OFFLINE_ENCRYPTION_DISABLED
ENV EXPO_PUBLIC_ENABLE_DEMO=$EXPO_PUBLIC_ENABLE_DEMO
ENV OIDC_ISSUER=$OIDC_ISSUER
ENV OIDC_CLIENT_ID=$OIDC_CLIENT_ID
ENV OIDC_AUDIENCE=$OIDC_AUDIENCE
ENV OIDC_SCOPE=$OIDC_SCOPE
ENV OIDC_REDIRECT_SCHEME=$OIDC_REDIRECT_SCHEME

RUN pnpm expo export --platform web

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
