# Generated by Django 5.0.14 on 2026-02-02 16:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("event_type", models.CharField(db_index=True, max_length=255)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "user_sub",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("scopes", models.TextField(blank=True)),
                ("resource_type", models.CharField(blank=True, max_length=255)),
                (
                    "resource_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("action", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=32)),
                ("http_status", models.IntegerField(null=True)),
                ("ip", models.CharField(blank=True, max_length=255)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "request_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("payload_hash", models.CharField(blank=True, max_length=64)),
                ("payload_size", models.IntegerField(blank=True, null=True)),
                ("meta", models.JSONField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
