import { CATEGORY, FHIR_CODES, SNOMED, TERMINOLOGY_SYSTEMS } from '../codes';

export const TEST_SYSTEMS = {
  LOINC: TERMINOLOGY_SYSTEMS.LOINC,
  UCUM: TERMINOLOGY_SYSTEMS.UCUM,
  SNOMED: TERMINOLOGY_SYSTEMS.SNOMED,
  OBSERVATION_CATEGORY: TERMINOLOGY_SYSTEMS.OBSERVATION_CATEGORY,
} as const;

export const TEST_CATEGORY_CODES = {
  VITAL_SIGNS: CATEGORY.vitalSigns.code,
  LABORATORY: CATEGORY.laboratory.code,
} as const;

export const TEST_VITAL_CODES = FHIR_CODES.VITALS;
export const TEST_SCALE_CODES = FHIR_CODES.SCALES;
export const TEST_RISK_CODES = FHIR_CODES.RISK;
export const TEST_CARE_CODES = FHIR_CODES.CARE;
export const TEST_SNOMED_CODES = SNOMED;
