name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      # Necesario para usar pip/genbadge en el runner
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # En PRs permitimos lockfile flexible para no bloquear iteración.
      # En main (push) exigimos lockfile consistente.
      - name: Install dependencies (PR)
        if: github.event_name == 'pull_request'
        run: pnpm install --no-frozen-lockfile

      - name: Install dependencies (push to main)
        if: github.event_name == 'push'
        run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm -w typecheck

      - name: Lint
        run: pnpm -w lint

      - name: Unit and integration tests
        run: pnpm -w vitest run --reporter=verbose --coverage --coverage.reporter=cobertura --coverage.reporter=lcov

      - name: Install python deps for genbadge
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel
          python -m pip install --upgrade genbadge

      - name: Coverage badge
        run: genbadge coverage -i coverage/cobertura-coverage.xml -o coverage-badge.svg


      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps

      - name: End-to-end tests
        run: pnpm -w test:e2e

      - name: Validate FHIR bundles
        run: pnpm -w validate:fhir

      - name: Upload unit coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-unit
          path: coverage/unit/lcov.info


